require: rubocop-rails

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.6.4
  Exclude:
    - 'spec/**/*'
    - 'lib/generators/**/*'
    - 'bin/rails'

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Rails/BelongsTo:
  Exclude:
    - 'app/models/spree/home_section_product.rb'

Layout/LineLength:
  Exclude:
    - 'spec'
    - 'app/overrides/spree/admin/shared/sub_menu/_configuration.rb'
